services:
  - type: web
    name: flow-forge-cms
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist

    pullRequestPreviewsEnabled: true

    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff

    envVars:
      - key: NODE_VERSION
        value: 20.19.0

      - key: VITE_API_URL
        value: https://api-flow.lynt.io

      - key: VITE_CMS_URL
        value: https://cms-flow.lynt.io

      - key: VITE_EDITOR_URL
        value: https://editor-flow.lynt.io